/**
 * @file LanguageContext.tsx
 * @description Контекст для управления языком приложения (9 языков)
 * @description Context for managing app language (9 languages)
 *
 * @author Bonds Team
 * @version 2.0.0
 * @license MIT
 */

import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useActionSheet, ActionSheetOption } from '../components/ActionSheet';

/**
 * Доступные языки / Available languages
 */
export type Language = 'ru' | 'en' | 'de' | 'uk' | 'it' | 'nl' | 'fr' | 'es' | 'bg';

/**
 * Метаданные для выбора языка (флаг + название на самом языке)
 * Metadata for the language picker (flag + native name)
 */
export const LANGUAGE_META: Record<Language, { flag: string; label: string }> = {
    ru: { flag: '🏳️', label: 'Русский' },
    en: { flag: '🇬🇧', label: 'English' },
    de: { flag: '🇩🇪', label: 'Deutsch' },
    uk: { flag: '🇺🇦', label: 'Українська' },
    it: { flag: '🇮🇹', label: 'Italiano' },
    nl: { flag: '🇳🇱', label: 'Nederlands' },
    fr: { flag: '🇫🇷', label: 'Français' },
    es: { flag: '🇪🇸', label: 'Español' },
    bg: { flag: '🇧🇬', label: 'Български' },
};

const LANGUAGE_ORDER: Language[] = ['ru', 'en', 'de', 'uk', 'it', 'nl', 'fr', 'es', 'bg'];

/**
 * Интерфейс контекста языка
 * Language context interface
 */
interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

/**
 * Переводы / Translations
 */
const translations: Record<Language, Record<string, string>> = {
    ru: {
        'app.name': 'Семейные мысли',
        'app.subtitle': 'Мысли парят в воздухе',
        'greeting': 'Привет',
        'friend': 'Друг',
        'select_chat': 'Выберите чат',
        'all_chats': 'Все',
        'group_chats': 'Групповые чаты',
        'group_chats_short': 'Группы',
        'private_chats': 'Личное',
        'no_chats': 'Нет чатов в этой категории',
        'soon': 'Скоро появятся!',
        'members': 'участников',
        'sort_recent': 'По активности',
        'sort_alpha': 'По алфавиту',
        'thoughts_float': 'Мысли парят в воздухе',
        'placeholder': 'Пиши...',
        'voice_message': 'Голосовое сообщение',
        'photo': 'Фото',
        'send': 'Отправить',
        'back': 'Назад',
        'error': 'Ошибка',
        'no_access': 'Нет доступа к галерее',
        'profile': 'Профиль',
        'username': 'Имя пользователя',
        'email': 'Email',
        'change_avatar': 'Сменить аватар',
        'avatar_upload_failed': 'Не удалось загрузить аватар',
        'choose_language': 'Выберите язык',
        'cancel': 'Отмена',
        'delete': 'Удалить',
        'reply': 'Ответить',
        'copy': 'Копировать',
        'edit': 'Редактировать',
        'ok': 'OK',
        'fill_all_fields': 'Заполните все поля',
        'mood_checkin_prompt': 'Как настроение сегодня? Ответь эмодзи 👇',
        'connection_not_ready': 'Соединение с чатом ещё не готово, попробуйте через секунду',
        'type_message_first': 'Сначала напишите текст в поле ввода',
        'mood_checkin_menu_item': '🙂 Чек-ин настроения',
        'time_capsule_menu_item': '🎁 Капсула времени',
        'checklist_menu_item': '☑️ Чек-лист',
        'select_text_first': 'Сначала выделите текст',
        'notebook_chat_name': '📓 Блокнот',
        'notebook_chat_label': '📓 Блокнот',
        'export_chat_menu_item': 'Экспорт переписки',
        'time_capsule_sealed': '🎁 Откроется {date}',
        'today': 'Сегодня',
        'yesterday': 'Вчера',
        'date_locale': 'ru-RU',
        'camera_permission_denied': 'Нет доступа к камере/микрофону',
        'incoming_call': 'Входящий звонок',
        'calling': 'Звоним…',
        'call_ended': 'Звонок завершён',
        'accept_call': 'Принять',
        'decline_call': 'Отклонить',
        'call_log_missed': '📞 Пропущенный звонок',
        'call_log_declined': '📞 Звонок отклонён',
        'call_log_cancelled': '📞 Звонок отменён',
        'call_log_answered': '📞 Звонок · {duration}',
        'open_in': 'Открыть через...',
        'pick_date_time': '📅 Выбрать дату и время',
        'in_an_hour': 'Час',
        'tomorrow': 'Завтра',
        'in_a_week': 'Неделю',
        'in_a_month': 'Месяц',
        'in_a_year': 'Год',
        'message_deleted': 'Сообщение удалено',
        'video': 'Видео',
        'file_label': 'Файл',
        'could_not_export_chat': 'Не удалось экспортировать чат',
        'no_mic_access': 'Нет доступа к микрофону',
        'could_not_start_recording': 'Не удалось начать запись',
        'could_not_send_voice': 'Не удалось отправить голосовое сообщение',
        'not_loaded_yet': 'Пока не загружено',
        'scroll_up_for_older': 'Прокрутите чат вверх, чтобы подгрузить более старые сообщения',
        'delete_message_confirm': 'Удалить сообщение?',
        'could_not_delete_message': 'Не удалось удалить сообщение',
        'could_not_edit_message': 'Не удалось изменить сообщение',
        'search_chat_placeholder': 'Поиск по чату',
        'search_chats_and_people_placeholder': 'Поиск чатов и людей',
        'start_new_chat_label': 'Начать новый чат',
        'participants_added': 'Участники добавлены',
        'could_not_load_chats': 'Не удалось загрузить чаты',
        'could_not_create_chat': 'Не удалось создать чат',
        'mute_chat': '🔕 Заглушить чат',
        'unmute_chat': '🔔 Включить уведомления',
        'leave_chat': 'Покинуть чат',
        'delete_for_everyone': 'Удалить для всех',
        'delete_chat': 'Удалить чат',
        'rename_chat': '✏️ Переименовать чат',
        'rename_chat_title': 'Переименовать чат',
        'could_not_rename_chat': 'Не удалось переименовать чат',
        'logout_confirm_title': 'Выйти из аккаунта?',
        'logout_confirm_message': 'Вы уверены?',
        'logout_confirm_button': 'Выйти',
        'enter_email': 'Введите email',
        'reset_code_sent_message': 'Если этот email зарегистрирован, на него отправлен код',
        'could_not_send_code': 'Не удалось отправить код',
        'password_reset_success': 'Пароль успешно изменён',
        'invalid_or_expired_code': 'Неверный или истёкший код',
        'enter_email_registered': 'Введите email, указанный при регистрации',
        'enter_code_and_new_password': 'Введите код из письма и новый пароль',
        'code_from_email_placeholder': 'Код из письма',
        'new_password_placeholder': 'Новый пароль',
        'enter_chat_name': 'Введите название чата',
        'chat_name_placeholder': 'Название чата',
        'group_chat_label': 'Групповой',
        'private_chat_label': 'Личный',
        'group_chat_description': '👥 Групповой чат для общения с несколькими людьми',
        'private_chat_description': '👤 Личный чат для общения один на один',
        'create_button': '➕ Создать',
        'could_not_load_participants': 'Не удалось загрузить участников',
        'remove_participant_confirm': 'Удалить участника?',
        'remove': 'Удалить',
        'could_not_remove_participant': 'Не удалось удалить участника',
        'you_suffix': '(вы)',
        'audio_link_missing': 'Ссылка на аудио отсутствует',
        'could_not_play_voice': 'Не удалось воспроизвести голосовое сообщение',
        'transcript_title': 'Транскрипция',
        'no_speech_recognized': 'Речь не распознана',
        'could_not_recognize_speech': 'Не удалось распознать речь',
        'no_speech_access': 'Нет доступа к распознаванию речи',
        'too_many_login_attempts': 'Слишком много неудачных попыток входа. Попробуйте позже',
        'invalid_credentials': 'Неверное имя пользователя или пароль',
        'too_many_otp_attempts': 'Слишком много неудачных попыток. Попробуйте позже',
        'enter_otp_code': 'Введите 6-значный код',
        'username_min_length': 'Имя пользователя должно содержать минимум 3 символа',
        'invalid_email': 'Введите корректный email',
        'passwords_dont_match': 'Пароли не совпадают',
        'registration_failed': 'Не удалось зарегистрироваться',
        'password_rules': 'Пароль: минимум 8 символов, заглавная и строчная буква, цифра',
        'sharing_not_available': 'Отправка недоступна на этом устройстве',
        'failed_to_send_video': 'Не удалось отправить видео',
        'failed_to_send_image': 'Не удалось отправить фото',
        'failed_to_send_file': 'Не удалось отправить файл',
        'forgot_password_title': 'Забыли пароль?',
        'send_code_button': 'Отправить код',
        'new_chat_title': 'Новый чат',
        'chat_type_label': 'Тип чата',
        'remove_participant_message': 'Убрать {name} из чата?',
        'participants_title': 'Участники чата',
        'add_participants_button': 'Добавить участников',
        'login_tagline': 'Ваша связь с близкими',
        'username_placeholder': 'Имя пользователя',
        'password_placeholder': 'Пароль',
        'forgot_password_link': 'Забыли пароль?',
        'create_account_link': 'Создать аккаунт',
        'verification_code_title': 'Код подтверждения',
        'otp_sent_message': 'Мы отправили код на вашу почту',
        'join_title': 'Присоединяйтесь',
        'create_account_subtitle': 'Создайте новый аккаунт',
        'confirm_password_placeholder': 'Повторите пароль',
        'already_have_account_link': 'Уже есть аккаунт? Войти',
        'select_at_least_one_user': 'Выберите хотя бы одного пользователя',
        'could_not_add_participants': 'Не удалось добавить участников',
        'search_users_placeholder': 'Поиск по имени или email...',
        'no_users_found': 'Пользователи не найдены',
        'selected_count': 'Выбрано',
        'add_button': 'Добавить',
        'nothing_found': 'Ничего не найдено',
        'edit_message_title': 'Редактировать сообщение',
        'save': 'Сохранить',
        'close': 'Закрыть',
        'year_ago_today_title': 'Год назад в этот день',
        'when_to_open_capsule': 'Когда открыть капсулу?',
        'done': 'Готово',
        'save_password_button': 'Сохранить пароль',
        'resend_code_link': 'Отправить код повторно',
    },
    en: {
        'app.name': 'Family Thoughts',
        'app.subtitle': 'Thoughts are floating in the air',
        'greeting': 'Hello',
        'friend': 'Friend',
        'select_chat': 'Select a chat',
        'all_chats': 'All',
        'group_chats': 'Group chats',
        'group_chats_short': 'Groups',
        'private_chats': 'Private',
        'no_chats': 'No chats in this category',
        'soon': 'Coming soon!',
        'members': 'members',
        'sort_recent': 'Recent',
        'sort_alpha': 'A-Z',
        'thoughts_float': 'Thoughts are floating in the air',
        'placeholder': 'Write...',
        'voice_message': 'Voice message',
        'photo': 'Photo',
        'send': 'Send',
        'back': 'Back',
        'error': 'Error',
        'no_access': 'No gallery access',
        'profile': 'Profile',
        'username': 'Username',
        'email': 'Email',
        'change_avatar': 'Change avatar',
        'avatar_upload_failed': 'Failed to upload avatar',
        'choose_language': 'Choose language',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'reply': 'Reply',
        'copy': 'Copy',
        'edit': 'Edit',
        'ok': 'OK',
        'fill_all_fields': 'Please fill all fields',
        'mood_checkin_prompt': 'How are you feeling today? React with an emoji 👇',
        'connection_not_ready': "Chat connection isn't ready yet, try again in a moment",
        'type_message_first': 'Type a message in the input first',
        'mood_checkin_menu_item': '🙂 Mood check-in',
        'time_capsule_menu_item': '🎁 Time capsule',
        'checklist_menu_item': '☑️ Checklist',
        'select_text_first': 'Select some text first',
        'notebook_chat_name': '📓 Notebook',
        'notebook_chat_label': '📓 Notebook',
        'export_chat_menu_item': 'Export chat',
        'time_capsule_sealed': '🎁 Opens {date}',
        'today': 'Today',
        'yesterday': 'Yesterday',
        'date_locale': 'en-US',
        'camera_permission_denied': 'No access to camera/microphone',
        'incoming_call': 'Incoming call',
        'calling': 'Calling…',
        'call_ended': 'Call ended',
        'accept_call': 'Accept',
        'decline_call': 'Decline',
        'call_log_missed': '📞 Missed call',
        'call_log_declined': '📞 Call declined',
        'call_log_cancelled': '📞 Call cancelled',
        'call_log_answered': '📞 Call · {duration}',
        'open_in': 'Open in...',
        'pick_date_time': '📅 Pick date & time',
        'in_an_hour': 'An hour',
        'tomorrow': 'Tomorrow',
        'in_a_week': 'A week',
        'in_a_month': 'A month',
        'in_a_year': 'A year',
        'message_deleted': 'Message deleted',
        'video': 'Video',
        'file_label': 'File',
        'could_not_export_chat': 'Could not export chat',
        'no_mic_access': 'No microphone access',
        'could_not_start_recording': 'Could not start recording',
        'could_not_send_voice': 'Could not send voice message',
        'not_loaded_yet': 'Not loaded yet',
        'scroll_up_for_older': 'Scroll up to load older messages',
        'delete_message_confirm': 'Delete message?',
        'could_not_delete_message': 'Could not delete message',
        'could_not_edit_message': 'Could not edit message',
        'search_chat_placeholder': 'Search chat',
        'search_chats_and_people_placeholder': 'Search chats and people',
        'start_new_chat_label': 'Start new chat',
        'participants_added': 'Participants added',
        'could_not_load_chats': 'Failed to load chats',
        'could_not_create_chat': 'Could not create chat',
        'mute_chat': '🔕 Mute chat',
        'unmute_chat': '🔔 Unmute',
        'leave_chat': 'Leave chat',
        'delete_for_everyone': 'Delete for everyone',
        'delete_chat': 'Delete chat',
        'rename_chat': '✏️ Rename chat',
        'rename_chat_title': 'Rename chat',
        'could_not_rename_chat': 'Could not rename chat',
        'logout_confirm_title': 'Log out?',
        'logout_confirm_message': 'Are you sure?',
        'logout_confirm_button': 'Log out',
        'enter_email': 'Enter your email',
        'reset_code_sent_message': 'If this email is registered, a code has been sent',
        'could_not_send_code': 'Could not send code',
        'password_reset_success': 'Password reset successfully',
        'invalid_or_expired_code': 'Invalid or expired code',
        'enter_email_registered': 'Enter the email you registered with',
        'enter_code_and_new_password': 'Enter the emailed code and a new password',
        'code_from_email_placeholder': 'Code from email',
        'new_password_placeholder': 'New password',
        'enter_chat_name': 'Enter chat name',
        'chat_name_placeholder': 'Chat name',
        'group_chat_label': 'Group',
        'private_chat_label': 'Private',
        'group_chat_description': '👥 Group chat for multiple people',
        'private_chat_description': '👤 Private chat for one-on-one conversation',
        'create_button': '➕ Create',
        'could_not_load_participants': 'Could not load participants',
        'remove_participant_confirm': 'Remove participant?',
        'remove': 'Remove',
        'could_not_remove_participant': 'Could not remove participant',
        'you_suffix': '(you)',
        'audio_link_missing': 'Audio link missing',
        'could_not_play_voice': 'Could not play voice message',
        'transcript_title': 'Transcript',
        'no_speech_recognized': 'No speech recognized',
        'could_not_recognize_speech': 'Could not recognize speech',
        'no_speech_access': 'No speech recognition access',
        'too_many_login_attempts': 'Too many failed login attempts. Try again later',
        'invalid_credentials': 'Invalid username or password',
        'too_many_otp_attempts': 'Too many failed attempts. Try again later',
        'enter_otp_code': 'Enter the 6-digit code',
        'username_min_length': 'Username must be at least 3 characters',
        'invalid_email': 'Enter a valid email',
        'passwords_dont_match': "Passwords don't match",
        'registration_failed': 'Registration failed',
        'password_rules': 'Password: at least 8 characters, one uppercase and lowercase letter, and a digit',
        'sharing_not_available': 'Sharing is not available on this device',
        'failed_to_send_video': 'Failed to send video',
        'failed_to_send_image': 'Failed to send image',
        'failed_to_send_file': 'Failed to send file',
        'forgot_password_title': 'Forgot password?',
        'send_code_button': 'Send code',
        'new_chat_title': 'New chat',
        'chat_type_label': 'Chat type',
        'remove_participant_message': 'Remove {name} from this chat?',
        'participants_title': 'Participants',
        'add_participants_button': 'Add participants',
        'login_tagline': 'Your bond with loved ones',
        'username_placeholder': 'Username',
        'password_placeholder': 'Password',
        'forgot_password_link': 'Forgot password?',
        'create_account_link': 'Create account',
        'verification_code_title': 'Verification code',
        'otp_sent_message': 'We sent a code to your email',
        'join_title': 'Join',
        'create_account_subtitle': 'Create a new account',
        'confirm_password_placeholder': 'Confirm password',
        'already_have_account_link': 'Already have an account? Login',
        'select_at_least_one_user': 'Select at least one user',
        'could_not_add_participants': 'Could not add participants',
        'search_users_placeholder': 'Search by name or email...',
        'no_users_found': 'No users found',
        'selected_count': 'Selected',
        'add_button': 'Add',
        'nothing_found': 'Nothing found',
        'edit_message_title': 'Edit message',
        'save': 'Save',
        'close': 'Close',
        'year_ago_today_title': 'A year ago today',
        'when_to_open_capsule': 'When to open the capsule?',
        'done': 'Done',
        'save_password_button': 'Save password',
        'resend_code_link': 'Resend code',
    },
    de: {
        'app.name': 'Familiengedanken',
        'app.subtitle': 'Gedanken schweben in der Luft',
        'greeting': 'Hallo',
        'friend': 'Freund',
        'select_chat': 'Chat auswählen',
        'all_chats': 'Alle',
        'group_chats': 'Gruppenchats',
        'group_chats_short': 'Gruppen',
        'private_chats': 'Privat',
        'no_chats': 'Keine Chats in dieser Kategorie',
        'soon': 'Bald verfügbar!',
        'members': 'Mitglieder',
        'sort_recent': 'Nach Aktivität',
        'sort_alpha': 'Alphabetisch',
        'thoughts_float': 'Gedanken schweben in der Luft',
        'placeholder': 'Schreib...',
        'voice_message': 'Sprachnachricht',
        'photo': 'Foto',
        'send': 'Senden',
        'back': 'Zurück',
        'error': 'Fehler',
        'no_access': 'Kein Zugriff auf die Galerie',
        'profile': 'Profil',
        'username': 'Benutzername',
        'email': 'E-Mail',
        'change_avatar': 'Avatar ändern',
        'avatar_upload_failed': 'Avatar konnte nicht hochgeladen werden',
        'choose_language': 'Sprache wählen',
        'cancel': 'Abbrechen',
        'delete': 'Löschen',
        'reply': 'Antworten',
        'copy': 'Kopieren',
        'edit': 'Bearbeiten',
        'ok': 'OK',
        'fill_all_fields': 'Bitte füllen Sie alle Felder aus',
        'mood_checkin_prompt': 'Wie fühlst du dich heute? Antworte mit einem Emoji 👇',
        'connection_not_ready': 'Die Chat-Verbindung ist noch nicht bereit, versuche es gleich noch einmal',
        'type_message_first': 'Schreib zuerst eine Nachricht in das Eingabefeld',
        'mood_checkin_menu_item': '🙂 Stimmungs-Check-in',
        'time_capsule_menu_item': '🎁 Zeitkapsel',
        'checklist_menu_item': '☑️ Checkliste',
        'select_text_first': 'Wählen Sie zuerst Text aus',
        'notebook_chat_name': '📓 Notizbuch',
        'notebook_chat_label': '📓 Notizbuch',
        'export_chat_menu_item': 'Chat exportieren',
        'time_capsule_sealed': '🎁 Öffnet sich {date}',
        'today': 'Heute',
        'yesterday': 'Gestern',
        'date_locale': 'de-DE',
        'camera_permission_denied': 'Kein Zugriff auf Kamera/Mikrofon',
        'incoming_call': 'Eingehender Anruf',
        'calling': 'Rufe an…',
        'call_ended': 'Anruf beendet',
        'accept_call': 'Annehmen',
        'decline_call': 'Ablehnen',
        'call_log_missed': '📞 Verpasster Anruf',
        'call_log_declined': '📞 Anruf abgelehnt',
        'call_log_cancelled': '📞 Anruf abgebrochen',
        'call_log_answered': '📞 Anruf · {duration}',
        'open_in': 'Öffnen mit...',
        'pick_date_time': '📅 Datum & Uhrzeit wählen',
        'in_an_hour': 'In einer Stunde',
        'tomorrow': 'Morgen',
        'in_a_week': 'In einer Woche',
        'in_a_month': 'In einem Monat',
        'in_a_year': 'In einem Jahr',
        'message_deleted': 'Nachricht gelöscht',
        'video': 'Video',
        'file_label': 'Datei',
        'could_not_export_chat': 'Chat konnte nicht exportiert werden',
        'no_mic_access': 'Kein Mikrofonzugriff',
        'could_not_start_recording': 'Aufnahme konnte nicht gestartet werden',
        'could_not_send_voice': 'Sprachnachricht konnte nicht gesendet werden',
        'not_loaded_yet': 'Noch nicht geladen',
        'scroll_up_for_older': 'Scrolle nach oben, um ältere Nachrichten zu laden',
        'delete_message_confirm': 'Nachricht löschen?',
        'could_not_delete_message': 'Nachricht konnte nicht gelöscht werden',
        'could_not_edit_message': 'Nachricht konnte nicht geändert werden',
        'search_chat_placeholder': 'Chat durchsuchen',
        'search_chats_and_people_placeholder': 'Chats und Personen durchsuchen',
        'start_new_chat_label': 'Neuen Chat starten',
        'participants_added': 'Teilnehmer hinzugefügt',
        'could_not_load_chats': 'Chats konnten nicht geladen werden',
        'could_not_create_chat': 'Chat konnte nicht erstellt werden',
        'mute_chat': '🔕 Chat stummschalten',
        'unmute_chat': '🔔 Stummschaltung aufheben',
        'leave_chat': 'Chat verlassen',
        'delete_for_everyone': 'Für alle löschen',
        'delete_chat': 'Chat löschen',
        'rename_chat': '✏️ Chat umbenennen',
        'rename_chat_title': 'Chat umbenennen',
        'could_not_rename_chat': 'Chat konnte nicht umbenannt werden',
        'logout_confirm_title': 'Abmelden?',
        'logout_confirm_message': 'Bist du sicher?',
        'logout_confirm_button': 'Abmelden',
        'enter_email': 'Gib deine E-Mail ein',
        'reset_code_sent_message': 'Wenn diese E-Mail registriert ist, wurde ein Code gesendet',
        'could_not_send_code': 'Code konnte nicht gesendet werden',
        'password_reset_success': 'Passwort erfolgreich geändert',
        'invalid_or_expired_code': 'Ungültiger oder abgelaufener Code',
        'enter_email_registered': 'Gib die E-Mail ein, mit der du dich registriert hast',
        'enter_code_and_new_password': 'Gib den Code aus der E-Mail und ein neues Passwort ein',
        'code_from_email_placeholder': 'Code aus der E-Mail',
        'new_password_placeholder': 'Neues Passwort',
        'enter_chat_name': 'Gib einen Chatnamen ein',
        'chat_name_placeholder': 'Chatname',
        'group_chat_label': 'Gruppe',
        'private_chat_label': 'Privat',
        'group_chat_description': '👥 Gruppenchat für mehrere Personen',
        'private_chat_description': '👤 Privater Chat für ein Gespräch unter vier Augen',
        'create_button': '➕ Erstellen',
        'could_not_load_participants': 'Teilnehmer konnten nicht geladen werden',
        'remove_participant_confirm': 'Teilnehmer entfernen?',
        'remove': 'Entfernen',
        'could_not_remove_participant': 'Teilnehmer konnte nicht entfernt werden',
        'you_suffix': '(du)',
        'audio_link_missing': 'Audio-Link fehlt',
        'could_not_play_voice': 'Sprachnachricht konnte nicht abgespielt werden',
        'transcript_title': 'Abschrift',
        'no_speech_recognized': 'Keine Sprache erkannt',
        'could_not_recognize_speech': 'Sprache konnte nicht erkannt werden',
        'no_speech_access': 'Kein Zugriff auf die Spracherkennung',
        'too_many_login_attempts': 'Zu viele fehlgeschlagene Anmeldeversuche. Versuche es später erneut',
        'invalid_credentials': 'Ungültiger Benutzername oder Passwort',
        'too_many_otp_attempts': 'Zu viele fehlgeschlagene Versuche. Versuche es später erneut',
        'enter_otp_code': 'Gib den 6-stelligen Code ein',
        'username_min_length': 'Der Benutzername muss mindestens 3 Zeichen lang sein',
        'invalid_email': 'Gib eine gültige E-Mail-Adresse ein',
        'passwords_dont_match': 'Die Passwörter stimmen nicht überein',
        'registration_failed': 'Registrierung fehlgeschlagen',
        'password_rules': 'Passwort: mindestens 8 Zeichen, ein Groß- und Kleinbuchstabe sowie eine Ziffer',
        'sharing_not_available': 'Teilen ist auf diesem Gerät nicht verfügbar',
        'failed_to_send_video': 'Video konnte nicht gesendet werden',
        'failed_to_send_image': 'Foto konnte nicht gesendet werden',
        'failed_to_send_file': 'Datei konnte nicht gesendet werden',
        'forgot_password_title': 'Passwort vergessen?',
        'send_code_button': 'Code senden',
        'new_chat_title': 'Neuer Chat',
        'chat_type_label': 'Chat-Typ',
        'remove_participant_message': '{name} aus dem Chat entfernen?',
        'participants_title': 'Teilnehmer',
        'add_participants_button': 'Teilnehmer hinzufügen',
        'login_tagline': 'Deine Verbindung zu den Liebsten',
        'username_placeholder': 'Benutzername',
        'password_placeholder': 'Passwort',
        'forgot_password_link': 'Passwort vergessen?',
        'create_account_link': 'Konto erstellen',
        'verification_code_title': 'Bestätigungscode',
        'otp_sent_message': 'Wir haben einen Code an deine E-Mail gesendet',
        'join_title': 'Mitmachen',
        'create_account_subtitle': 'Erstelle ein neues Konto',
        'confirm_password_placeholder': 'Passwort bestätigen',
        'already_have_account_link': 'Schon ein Konto? Anmelden',
        'select_at_least_one_user': 'Wähle mindestens eine Person aus',
        'could_not_add_participants': 'Teilnehmer konnten nicht hinzugefügt werden',
        'search_users_placeholder': 'Nach Name oder E-Mail suchen...',
        'no_users_found': 'Keine Benutzer gefunden',
        'selected_count': 'Ausgewählt',
        'add_button': 'Hinzufügen',
        'nothing_found': 'Nichts gefunden',
        'edit_message_title': 'Nachricht bearbeiten',
        'save': 'Speichern',
        'close': 'Schließen',
        'year_ago_today_title': 'Vor einem Jahr an diesem Tag',
        'when_to_open_capsule': 'Wann soll die Kapsel geöffnet werden?',
        'done': 'Fertig',
        'save_password_button': 'Passwort speichern',
        'resend_code_link': 'Code erneut senden',
    },
    uk: {
        'app.name': 'Сімейні думки',
        'app.subtitle': 'Думки витають у повітрі',
        'greeting': 'Привіт',
        'friend': 'Друже',
        'select_chat': 'Виберіть чат',
        'all_chats': 'Усі',
        'group_chats': 'Групові чати',
        'group_chats_short': 'Групи',
        'private_chats': 'Особисті',
        'no_chats': 'Немає чатів у цій категорії',
        'soon': 'Скоро з’являться!',
        'members': 'учасників',
        'sort_recent': 'За активністю',
        'sort_alpha': 'За алфавітом',
        'thoughts_float': 'Думки витають у повітрі',
        'placeholder': 'Пиши...',
        'voice_message': 'Голосове повідомлення',
        'photo': 'Фото',
        'send': 'Надіслати',
        'back': 'Назад',
        'error': 'Помилка',
        'no_access': 'Немає доступу до галереї',
        'profile': 'Профіль',
        'username': 'Ім’я користувача',
        'email': 'Email',
        'change_avatar': 'Змінити аватар',
        'avatar_upload_failed': 'Не вдалося завантажити аватар',
        'choose_language': 'Виберіть мову',
        'cancel': 'Скасувати',
        'delete': 'Видалити',
        'reply': 'Відповісти',
        'copy': 'Копіювати',
        'edit': 'Редагувати',
        'ok': 'OK',
        'fill_all_fields': 'Заповніть усі поля',
        'mood_checkin_prompt': 'Який у тебе настрій сьогодні? Відповідай емодзі 👇',
        'connection_not_ready': 'З’єднання з чатом ще не готове, спробуйте за мить',
        'type_message_first': 'Спочатку напишіть текст у полі вводу',
        'mood_checkin_menu_item': '🙂 Чек-ін настрою',
        'time_capsule_menu_item': '🎁 Капсула часу',
        'checklist_menu_item': '☑️ Чек-лист',
        'select_text_first': 'Спочатку виділіть текст',
        'notebook_chat_name': '📓 Блокнот',
        'notebook_chat_label': '📓 Блокнот',
        'export_chat_menu_item': 'Експорт переписки',
        'time_capsule_sealed': '🎁 Відкриється {date}',
        'today': 'Сьогодні',
        'yesterday': 'Вчора',
        'date_locale': 'uk-UA',
        'camera_permission_denied': 'Немає доступу до камери/мікрофона',
        'incoming_call': 'Вхідний дзвінок',
        'calling': 'Дзвонимо…',
        'call_ended': 'Дзвінок завершено',
        'accept_call': 'Прийняти',
        'decline_call': 'Відхилити',
        'call_log_missed': '📞 Пропущений дзвінок',
        'call_log_declined': '📞 Дзвінок відхилено',
        'call_log_cancelled': '📞 Дзвінок скасовано',
        'call_log_answered': '📞 Дзвінок · {duration}',
        'open_in': 'Відкрити через...',
        'pick_date_time': '📅 Обрати дату й час',
        'in_an_hour': 'Годину',
        'tomorrow': 'Завтра',
        'in_a_week': 'Тиждень',
        'in_a_month': 'Місяць',
        'in_a_year': 'Рік',
        'message_deleted': 'Повідомлення видалено',
        'video': 'Відео',
        'file_label': 'Файл',
        'could_not_export_chat': 'Не вдалося експортувати чат',
        'no_mic_access': 'Немає доступу до мікрофона',
        'could_not_start_recording': 'Не вдалося почати запис',
        'could_not_send_voice': 'Не вдалося надіслати голосове повідомлення',
        'not_loaded_yet': 'Ще не завантажено',
        'scroll_up_for_older': 'Прокрутіть чат вгору, щоб завантажити старіші повідомлення',
        'delete_message_confirm': 'Видалити повідомлення?',
        'could_not_delete_message': 'Не вдалося видалити повідомлення',
        'could_not_edit_message': 'Не вдалося змінити повідомлення',
        'search_chat_placeholder': 'Пошук у чаті',
        'search_chats_and_people_placeholder': 'Пошук чатів і людей',
        'start_new_chat_label': 'Почати новий чат',
        'participants_added': 'Учасників додано',
        'could_not_load_chats': 'Не вдалося завантажити чати',
        'could_not_create_chat': 'Не вдалося створити чат',
        'mute_chat': '🔕 Вимкнути сповіщення',
        'unmute_chat': '🔔 Увімкнути сповіщення',
        'leave_chat': 'Покинути чат',
        'delete_for_everyone': 'Видалити для всіх',
        'delete_chat': 'Видалити чат',
        'rename_chat': '✏️ Перейменувати чат',
        'rename_chat_title': 'Перейменувати чат',
        'could_not_rename_chat': 'Не вдалося перейменувати чат',
        'logout_confirm_title': 'Вийти з акаунта?',
        'logout_confirm_message': 'Ви впевнені?',
        'logout_confirm_button': 'Вийти',
        'enter_email': 'Введіть email',
        'reset_code_sent_message': 'Якщо цей email зареєстровано, на нього надіслано код',
        'could_not_send_code': 'Не вдалося надіслати код',
        'password_reset_success': 'Пароль успішно змінено',
        'invalid_or_expired_code': 'Невірний або прострочений код',
        'enter_email_registered': 'Введіть email, вказаний під час реєстрації',
        'enter_code_and_new_password': 'Введіть код з листа та новий пароль',
        'code_from_email_placeholder': 'Код з листа',
        'new_password_placeholder': 'Новий пароль',
        'enter_chat_name': 'Введіть назву чату',
        'chat_name_placeholder': 'Назва чату',
        'group_chat_label': 'Груповий',
        'private_chat_label': 'Особистий',
        'group_chat_description': '👥 Груповий чат для спілкування з кількома людьми',
        'private_chat_description': '👤 Особистий чат для спілкування один на один',
        'create_button': '➕ Створити',
        'could_not_load_participants': 'Не вдалося завантажити учасників',
        'remove_participant_confirm': 'Видалити учасника?',
        'remove': 'Видалити',
        'could_not_remove_participant': 'Не вдалося видалити учасника',
        'you_suffix': '(ви)',
        'audio_link_missing': 'Посилання на аудіо відсутнє',
        'could_not_play_voice': 'Не вдалося відтворити голосове повідомлення',
        'transcript_title': 'Транскрипція',
        'no_speech_recognized': 'Мову не розпізнано',
        'could_not_recognize_speech': 'Не вдалося розпізнати мову',
        'no_speech_access': 'Немає доступу до розпізнавання мови',
        'too_many_login_attempts': 'Забагато невдалих спроб входу. Спробуйте пізніше',
        'invalid_credentials': 'Невірне ім’я користувача або пароль',
        'too_many_otp_attempts': 'Забагато невдалих спроб. Спробуйте пізніше',
        'enter_otp_code': 'Введіть 6-значний код',
        'username_min_length': 'Ім’я користувача має містити щонайменше 3 символи',
        'invalid_email': 'Введіть коректний email',
        'passwords_dont_match': 'Паролі не збігаються',
        'registration_failed': 'Не вдалося зареєструватися',
        'password_rules': 'Пароль: щонайменше 8 символів, велика й мала літера, цифра',
        'sharing_not_available': 'Надсилання недоступне на цьому пристрої',
        'failed_to_send_video': 'Не вдалося надіслати відео',
        'failed_to_send_image': 'Не вдалося надіслати фото',
        'failed_to_send_file': 'Не вдалося надіслати файл',
        'forgot_password_title': 'Забули пароль?',
        'send_code_button': 'Надіслати код',
        'new_chat_title': 'Новий чат',
        'chat_type_label': 'Тип чату',
        'remove_participant_message': 'Прибрати {name} з чату?',
        'participants_title': 'Учасники чату',
        'add_participants_button': 'Додати учасників',
        'login_tagline': 'Ваш зв’язок з рідними',
        'username_placeholder': 'Ім’я користувача',
        'password_placeholder': 'Пароль',
        'forgot_password_link': 'Забули пароль?',
        'create_account_link': 'Створити акаунт',
        'verification_code_title': 'Код підтвердження',
        'otp_sent_message': 'Ми надіслали код на вашу пошту',
        'join_title': 'Приєднуйтесь',
        'create_account_subtitle': 'Створіть новий акаунт',
        'confirm_password_placeholder': 'Повторіть пароль',
        'already_have_account_link': 'Вже є акаунт? Увійти',
        'select_at_least_one_user': 'Виберіть хоча б одного користувача',
        'could_not_add_participants': 'Не вдалося додати учасників',
        'search_users_placeholder': 'Пошук за іменем або email...',
        'no_users_found': 'Користувачів не знайдено',
        'selected_count': 'Обрано',
        'add_button': 'Додати',
        'nothing_found': 'Нічого не знайдено',
        'edit_message_title': 'Редагувати повідомлення',
        'save': 'Зберегти',
        'close': 'Закрити',
        'year_ago_today_title': 'Рік тому цього дня',
        'when_to_open_capsule': 'Коли відкрити капсулу?',
        'done': 'Готово',
        'save_password_button': 'Зберегти пароль',
        'resend_code_link': 'Надіслати код повторно',
    },
    it: {
        'app.name': 'Pensieri di famiglia',
        'app.subtitle': 'I pensieri fluttuano nell’aria',
        'greeting': 'Ciao',
        'friend': 'Amico',
        'select_chat': 'Seleziona una chat',
        'all_chats': 'Tutte',
        'group_chats': 'Chat di gruppo',
        'group_chats_short': 'Gruppi',
        'private_chats': 'Private',
        'no_chats': 'Nessuna chat in questa categoria',
        'soon': 'In arrivo presto!',
        'members': 'membri',
        'sort_recent': 'Recenti',
        'sort_alpha': 'A-Z',
        'thoughts_float': 'I pensieri fluttuano nell’aria',
        'placeholder': 'Scrivi...',
        'voice_message': 'Messaggio vocale',
        'photo': 'Foto',
        'send': 'Invia',
        'back': 'Indietro',
        'error': 'Errore',
        'no_access': 'Nessun accesso alla galleria',
        'profile': 'Profilo',
        'username': 'Nome utente',
        'email': 'Email',
        'change_avatar': 'Cambia avatar',
        'avatar_upload_failed': 'Impossibile caricare l’avatar',
        'choose_language': 'Scegli la lingua',
        'cancel': 'Annulla',
        'delete': 'Elimina',
        'reply': 'Rispondi',
        'copy': 'Copia',
        'edit': 'Modifica',
        'ok': 'OK',
        'fill_all_fields': 'Compila tutti i campi',
        'mood_checkin_prompt': 'Come ti senti oggi? Rispondi con un’emoji 👇',
        'connection_not_ready': 'La connessione alla chat non è ancora pronta, riprova tra un momento',
        'type_message_first': 'Scrivi prima un messaggio nel campo di testo',
        'mood_checkin_menu_item': '🙂 Check-in dell’umore',
        'time_capsule_menu_item': '🎁 Capsula del tempo',
        'checklist_menu_item': '☑️ Lista di controllo',
        'select_text_first': 'Seleziona prima del testo',
        'notebook_chat_name': '📓 Blocco note',
        'notebook_chat_label': '📓 Blocco note',
        'export_chat_menu_item': 'Esporta chat',
        'time_capsule_sealed': '🎁 Si apre {date}',
        'today': 'Oggi',
        'yesterday': 'Ieri',
        'date_locale': 'it-IT',
        'camera_permission_denied': 'Nessun accesso a fotocamera/microfono',
        'incoming_call': 'Chiamata in arrivo',
        'calling': 'Chiamata in corso…',
        'call_ended': 'Chiamata terminata',
        'accept_call': 'Accetta',
        'decline_call': 'Rifiuta',
        'call_log_missed': '📞 Chiamata persa',
        'call_log_declined': '📞 Chiamata rifiutata',
        'call_log_cancelled': '📞 Chiamata annullata',
        'call_log_answered': '📞 Chiamata · {duration}',
        'open_in': 'Apri con...',
        'pick_date_time': '📅 Scegli data e ora',
        'in_an_hour': 'Tra un’ora',
        'tomorrow': 'Domani',
        'in_a_week': 'Tra una settimana',
        'in_a_month': 'Tra un mese',
        'in_a_year': 'Tra un anno',
        'message_deleted': 'Messaggio eliminato',
        'video': 'Video',
        'file_label': 'File',
        'could_not_export_chat': 'Impossibile esportare la chat',
        'no_mic_access': 'Nessun accesso al microfono',
        'could_not_start_recording': 'Impossibile avviare la registrazione',
        'could_not_send_voice': 'Impossibile inviare il messaggio vocale',
        'not_loaded_yet': 'Non ancora caricato',
        'scroll_up_for_older': 'Scorri verso l’alto per caricare i messaggi più vecchi',
        'delete_message_confirm': 'Eliminare il messaggio?',
        'could_not_delete_message': 'Impossibile eliminare il messaggio',
        'could_not_edit_message': 'Impossibile modificare il messaggio',
        'search_chat_placeholder': 'Cerca nella chat',
        'search_chats_and_people_placeholder': 'Cerca chat e persone',
        'start_new_chat_label': 'Inizia una nuova chat',
        'participants_added': 'Partecipanti aggiunti',
        'could_not_load_chats': 'Impossibile caricare le chat',
        'could_not_create_chat': 'Impossibile creare la chat',
        'mute_chat': '🔕 Silenzia chat',
        'unmute_chat': '🔔 Riattiva notifiche',
        'leave_chat': 'Abbandona la chat',
        'delete_for_everyone': 'Elimina per tutti',
        'delete_chat': 'Elimina chat',
        'rename_chat': '✏️ Rinomina chat',
        'rename_chat_title': 'Rinomina chat',
        'could_not_rename_chat': 'Impossibile rinominare la chat',
        'logout_confirm_title': 'Vuoi disconnetterti?',
        'logout_confirm_message': 'Sei sicuro?',
        'logout_confirm_button': 'Disconnetti',
        'enter_email': 'Inserisci la tua email',
        'reset_code_sent_message': 'Se questa email è registrata, è stato inviato un codice',
        'could_not_send_code': 'Impossibile inviare il codice',
        'password_reset_success': 'Password reimpostata con successo',
        'invalid_or_expired_code': 'Codice non valido o scaduto',
        'enter_email_registered': 'Inserisci l’email con cui ti sei registrato',
        'enter_code_and_new_password': 'Inserisci il codice ricevuto via email e una nuova password',
        'code_from_email_placeholder': 'Codice dall’email',
        'new_password_placeholder': 'Nuova password',
        'enter_chat_name': 'Inserisci il nome della chat',
        'chat_name_placeholder': 'Nome della chat',
        'group_chat_label': 'Gruppo',
        'private_chat_label': 'Privata',
        'group_chat_description': '👥 Chat di gruppo per più persone',
        'private_chat_description': '👤 Chat privata per una conversazione uno a uno',
        'create_button': '➕ Crea',
        'could_not_load_participants': 'Impossibile caricare i partecipanti',
        'remove_participant_confirm': 'Rimuovere il partecipante?',
        'remove': 'Rimuovi',
        'could_not_remove_participant': 'Impossibile rimuovere il partecipante',
        'you_suffix': '(tu)',
        'audio_link_missing': 'Link audio mancante',
        'could_not_play_voice': 'Impossibile riprodurre il messaggio vocale',
        'transcript_title': 'Trascrizione',
        'no_speech_recognized': 'Nessun parlato riconosciuto',
        'could_not_recognize_speech': 'Impossibile riconoscere il parlato',
        'no_speech_access': 'Nessun accesso al riconoscimento vocale',
        'too_many_login_attempts': 'Troppi tentativi di accesso falliti. Riprova più tardi',
        'invalid_credentials': 'Nome utente o password non validi',
        'too_many_otp_attempts': 'Troppi tentativi falliti. Riprova più tardi',
        'enter_otp_code': 'Inserisci il codice a 6 cifre',
        'username_min_length': 'Il nome utente deve contenere almeno 3 caratteri',
        'invalid_email': 'Inserisci un’email valida',
        'passwords_dont_match': 'Le password non coincidono',
        'registration_failed': 'Registrazione non riuscita',
        'password_rules': 'Password: almeno 8 caratteri, una maiuscola, una minuscola e una cifra',
        'sharing_not_available': 'La condivisione non è disponibile su questo dispositivo',
        'failed_to_send_video': 'Impossibile inviare il video',
        'failed_to_send_image': 'Impossibile inviare la foto',
        'failed_to_send_file': 'Impossibile inviare il file',
        'forgot_password_title': 'Password dimenticata?',
        'send_code_button': 'Invia codice',
        'new_chat_title': 'Nuova chat',
        'chat_type_label': 'Tipo di chat',
        'remove_participant_message': 'Rimuovere {name} dalla chat?',
        'participants_title': 'Partecipanti',
        'add_participants_button': 'Aggiungi partecipanti',
        'login_tagline': 'Il tuo legame con le persone care',
        'username_placeholder': 'Nome utente',
        'password_placeholder': 'Password',
        'forgot_password_link': 'Password dimenticata?',
        'create_account_link': 'Crea account',
        'verification_code_title': 'Codice di verifica',
        'otp_sent_message': 'Abbiamo inviato un codice alla tua email',
        'join_title': 'Unisciti',
        'create_account_subtitle': 'Crea un nuovo account',
        'confirm_password_placeholder': 'Conferma password',
        'already_have_account_link': 'Hai già un account? Accedi',
        'select_at_least_one_user': 'Seleziona almeno un utente',
        'could_not_add_participants': 'Impossibile aggiungere i partecipanti',
        'search_users_placeholder': 'Cerca per nome o email...',
        'no_users_found': 'Nessun utente trovato',
        'selected_count': 'Selezionati',
        'add_button': 'Aggiungi',
        'nothing_found': 'Nessun risultato',
        'edit_message_title': 'Modifica messaggio',
        'save': 'Salva',
        'close': 'Chiudi',
        'year_ago_today_title': 'Un anno fa, oggi',
        'when_to_open_capsule': 'Quando aprire la capsula?',
        'done': 'Fatto',
        'save_password_button': 'Salva password',
        'resend_code_link': 'Invia di nuovo il codice',
    },
    nl: {
        'app.name': 'Familiegedachten',
        'app.subtitle': 'Gedachten zweven in de lucht',
        'greeting': 'Hallo',
        'friend': 'Vriend',
        'select_chat': 'Kies een chat',
        'all_chats': 'Alle',
        'group_chats': 'Groepschats',
        'group_chats_short': 'Groepen',
        'private_chats': 'Privé',
        'no_chats': 'Geen chats in deze categorie',
        'soon': 'Binnenkort beschikbaar!',
        'members': 'leden',
        'sort_recent': 'Op activiteit',
        'sort_alpha': 'Alfabetisch',
        'thoughts_float': 'Gedachten zweven in de lucht',
        'placeholder': 'Schrijf...',
        'voice_message': 'Spraakbericht',
        'photo': 'Foto',
        'send': 'Verzenden',
        'back': 'Terug',
        'error': 'Fout',
        'no_access': 'Geen toegang tot de galerij',
        'profile': 'Profiel',
        'username': 'Gebruikersnaam',
        'email': 'E-mail',
        'change_avatar': 'Avatar wijzigen',
        'avatar_upload_failed': 'Avatar uploaden mislukt',
        'choose_language': 'Kies taal',
        'cancel': 'Annuleren',
        'delete': 'Verwijderen',
        'reply': 'Beantwoorden',
        'copy': 'Kopiëren',
        'edit': 'Bewerken',
        'ok': 'OK',
        'fill_all_fields': 'Vul alle velden in',
        'mood_checkin_prompt': 'Hoe voel je je vandaag? Reageer met een emoji 👇',
        'connection_not_ready': 'De chatverbinding is nog niet klaar, probeer het zo weer',
        'type_message_first': 'Schrijf eerst een bericht in het invoerveld',
        'mood_checkin_menu_item': '🙂 Stemmings-check-in',
        'time_capsule_menu_item': '🎁 Tijdcapsule',
        'checklist_menu_item': '☑️ Checklist',
        'select_text_first': 'Selecteer eerst tekst',
        'notebook_chat_name': '📓 Notitieboek',
        'notebook_chat_label': '📓 Notitieboek',
        'export_chat_menu_item': 'Chat exporteren',
        'time_capsule_sealed': '🎁 Gaat open {date}',
        'today': 'Vandaag',
        'yesterday': 'Gisteren',
        'date_locale': 'nl-NL',
        'camera_permission_denied': 'Geen toegang tot camera/microfoon',
        'incoming_call': 'Inkomend gesprek',
        'calling': 'Bellen…',
        'call_ended': 'Gesprek beëindigd',
        'accept_call': 'Opnemen',
        'decline_call': 'Weigeren',
        'call_log_missed': '📞 Gemiste oproep',
        'call_log_declined': '📞 Oproep geweigerd',
        'call_log_cancelled': '📞 Oproep geannuleerd',
        'call_log_answered': '📞 Oproep · {duration}',
        'open_in': 'Openen met...',
        'pick_date_time': '📅 Datum & tijd kiezen',
        'in_an_hour': 'Over een uur',
        'tomorrow': 'Morgen',
        'in_a_week': 'Over een week',
        'in_a_month': 'Over een maand',
        'in_a_year': 'Over een jaar',
        'message_deleted': 'Bericht verwijderd',
        'video': 'Video',
        'file_label': 'Bestand',
        'could_not_export_chat': 'Chat kon niet worden geëxporteerd',
        'no_mic_access': 'Geen toegang tot de microfoon',
        'could_not_start_recording': 'Opname kon niet worden gestart',
        'could_not_send_voice': 'Spraakbericht kon niet worden verzonden',
        'not_loaded_yet': 'Nog niet geladen',
        'scroll_up_for_older': 'Scroll omhoog om oudere berichten te laden',
        'delete_message_confirm': 'Bericht verwijderen?',
        'could_not_delete_message': 'Bericht kon niet worden verwijderd',
        'could_not_edit_message': 'Bericht kon niet worden gewijzigd',
        'search_chat_placeholder': 'Chat doorzoeken',
        'search_chats_and_people_placeholder': 'Chats en mensen zoeken',
        'start_new_chat_label': 'Nieuwe chat starten',
        'participants_added': 'Deelnemers toegevoegd',
        'could_not_load_chats': 'Chats konden niet worden geladen',
        'could_not_create_chat': 'Chat kon niet worden aangemaakt',
        'mute_chat': '🔕 Chat dempen',
        'unmute_chat': '🔔 Demping opheffen',
        'leave_chat': 'Chat verlaten',
        'delete_for_everyone': 'Verwijderen voor iedereen',
        'delete_chat': 'Chat verwijderen',
        'rename_chat': '✏️ Chat hernoemen',
        'rename_chat_title': 'Chat hernoemen',
        'could_not_rename_chat': 'Kon chat niet hernoemen',
        'logout_confirm_title': 'Uitloggen?',
        'logout_confirm_message': 'Weet je het zeker?',
        'logout_confirm_button': 'Uitloggen',
        'enter_email': 'Voer je e-mailadres in',
        'reset_code_sent_message': 'Als dit e-mailadres geregistreerd is, is er een code verzonden',
        'could_not_send_code': 'Code kon niet worden verzonden',
        'password_reset_success': 'Wachtwoord succesvol gewijzigd',
        'invalid_or_expired_code': 'Ongeldige of verlopen code',
        'enter_email_registered': 'Voer het e-mailadres in waarmee je bent geregistreerd',
        'enter_code_and_new_password': 'Voer de code uit de e-mail en een nieuw wachtwoord in',
        'code_from_email_placeholder': 'Code uit de e-mail',
        'new_password_placeholder': 'Nieuw wachtwoord',
        'enter_chat_name': 'Voer een chatnaam in',
        'chat_name_placeholder': 'Chatnaam',
        'group_chat_label': 'Groep',
        'private_chat_label': 'Privé',
        'group_chat_description': '👥 Groepschat voor meerdere personen',
        'private_chat_description': '👤 Privéchat voor een gesprek onder vier ogen',
        'create_button': '➕ Aanmaken',
        'could_not_load_participants': 'Deelnemers konden niet worden geladen',
        'remove_participant_confirm': 'Deelnemer verwijderen?',
        'remove': 'Verwijderen',
        'could_not_remove_participant': 'Deelnemer kon niet worden verwijderd',
        'you_suffix': '(jij)',
        'audio_link_missing': 'Audiolink ontbreekt',
        'could_not_play_voice': 'Spraakbericht kon niet worden afgespeeld',
        'transcript_title': 'Transcript',
        'no_speech_recognized': 'Geen spraak herkend',
        'could_not_recognize_speech': 'Spraak kon niet worden herkend',
        'no_speech_access': 'Geen toegang tot spraakherkenning',
        'too_many_login_attempts': 'Te veel mislukte inlogpogingen. Probeer het later opnieuw',
        'invalid_credentials': 'Ongeldige gebruikersnaam of wachtwoord',
        'too_many_otp_attempts': 'Te veel mislukte pogingen. Probeer het later opnieuw',
        'enter_otp_code': 'Voer de 6-cijferige code in',
        'username_min_length': 'Gebruikersnaam moet minimaal 3 tekens bevatten',
        'invalid_email': 'Voer een geldig e-mailadres in',
        'passwords_dont_match': 'Wachtwoorden komen niet overeen',
        'registration_failed': 'Registratie mislukt',
        'password_rules': 'Wachtwoord: minimaal 8 tekens, een hoofdletter, kleine letter en een cijfer',
        'sharing_not_available': 'Delen is niet beschikbaar op dit apparaat',
        'failed_to_send_video': 'Video kon niet worden verzonden',
        'failed_to_send_image': 'Foto kon niet worden verzonden',
        'failed_to_send_file': 'Bestand kon niet worden verzonden',
        'forgot_password_title': 'Wachtwoord vergeten?',
        'send_code_button': 'Code verzenden',
        'new_chat_title': 'Nieuwe chat',
        'chat_type_label': 'Chattype',
        'remove_participant_message': '{name} uit deze chat verwijderen?',
        'participants_title': 'Deelnemers',
        'add_participants_button': 'Deelnemers toevoegen',
        'login_tagline': 'Jouw band met dierbaren',
        'username_placeholder': 'Gebruikersnaam',
        'password_placeholder': 'Wachtwoord',
        'forgot_password_link': 'Wachtwoord vergeten?',
        'create_account_link': 'Account aanmaken',
        'verification_code_title': 'Verificatiecode',
        'otp_sent_message': 'We hebben een code naar je e-mail gestuurd',
        'join_title': 'Doe mee',
        'create_account_subtitle': 'Maak een nieuw account aan',
        'confirm_password_placeholder': 'Bevestig wachtwoord',
        'already_have_account_link': 'Al een account? Inloggen',
        'select_at_least_one_user': 'Selecteer minstens één gebruiker',
        'could_not_add_participants': 'Deelnemers konden niet worden toegevoegd',
        'search_users_placeholder': 'Zoek op naam of e-mail...',
        'no_users_found': 'Geen gebruikers gevonden',
        'selected_count': 'Geselecteerd',
        'add_button': 'Toevoegen',
        'nothing_found': 'Niets gevonden',
        'edit_message_title': 'Bericht bewerken',
        'save': 'Opslaan',
        'close': 'Sluiten',
        'year_ago_today_title': 'Een jaar geleden vandaag',
        'when_to_open_capsule': 'Wanneer moet de capsule opengaan?',
        'done': 'Klaar',
        'save_password_button': 'Wachtwoord opslaan',
        'resend_code_link': 'Code opnieuw verzenden',
    },
    fr: {
        'app.name': 'Pensées de famille',
        'app.subtitle': 'Les pensées flottent dans l’air',
        'greeting': 'Salut',
        'friend': 'Ami',
        'select_chat': 'Choisir une discussion',
        'all_chats': 'Toutes',
        'group_chats': 'Discussions de groupe',
        'group_chats_short': 'Groupes',
        'private_chats': 'Privées',
        'no_chats': 'Aucune discussion dans cette catégorie',
        'soon': 'Bientôt disponible !',
        'members': 'membres',
        'sort_recent': 'Récentes',
        'sort_alpha': 'A-Z',
        'thoughts_float': 'Les pensées flottent dans l’air',
        'placeholder': 'Écris...',
        'voice_message': 'Message vocal',
        'photo': 'Photo',
        'send': 'Envoyer',
        'back': 'Retour',
        'error': 'Erreur',
        'no_access': 'Pas d’accès à la galerie',
        'profile': 'Profil',
        'username': 'Nom d’utilisateur',
        'email': 'Email',
        'change_avatar': 'Changer l’avatar',
        'avatar_upload_failed': 'Échec du téléchargement de l’avatar',
        'choose_language': 'Choisir la langue',
        'cancel': 'Annuler',
        'delete': 'Supprimer',
        'reply': 'Répondre',
        'copy': 'Copier',
        'edit': 'Modifier',
        'ok': 'OK',
        'fill_all_fields': 'Veuillez remplir tous les champs',
        'mood_checkin_prompt': 'Comment te sens-tu aujourd’hui ? Réponds avec un emoji 👇',
        'connection_not_ready': 'La connexion au chat n’est pas encore prête, réessaie dans un instant',
        'type_message_first': 'Écris d’abord un message dans le champ de saisie',
        'mood_checkin_menu_item': '🙂 Suivi d’humeur',
        'time_capsule_menu_item': '🎁 Capsule temporelle',
        'checklist_menu_item': '☑️ Liste de contrôle',
        'select_text_first': 'Sélectionnez d’abord du texte',
        'notebook_chat_name': '📓 Bloc-notes',
        'notebook_chat_label': '📓 Bloc-notes',
        'export_chat_menu_item': 'Exporter la conversation',
        'time_capsule_sealed': '🎁 Ouverture {date}',
        'today': 'Aujourd’hui',
        'yesterday': 'Hier',
        'date_locale': 'fr-FR',
        'camera_permission_denied': 'Pas d’accès à la caméra/au micro',
        'incoming_call': 'Appel entrant',
        'calling': 'Appel en cours…',
        'call_ended': 'Appel terminé',
        'accept_call': 'Répondre',
        'decline_call': 'Refuser',
        'call_log_missed': '📞 Appel manqué',
        'call_log_declined': '📞 Appel refusé',
        'call_log_cancelled': '📞 Appel annulé',
        'call_log_answered': '📞 Appel · {duration}',
        'open_in': 'Ouvrir avec...',
        'pick_date_time': '📅 Choisir la date et l’heure',
        'in_an_hour': 'Dans une heure',
        'tomorrow': 'Demain',
        'in_a_week': 'Dans une semaine',
        'in_a_month': 'Dans un mois',
        'in_a_year': 'Dans un an',
        'message_deleted': 'Message supprimé',
        'video': 'Vidéo',
        'file_label': 'Fichier',
        'could_not_export_chat': 'Impossible d’exporter la discussion',
        'no_mic_access': 'Pas d’accès au microphone',
        'could_not_start_recording': 'Impossible de démarrer l’enregistrement',
        'could_not_send_voice': 'Impossible d’envoyer le message vocal',
        'not_loaded_yet': 'Pas encore chargé',
        'scroll_up_for_older': 'Fais défiler vers le haut pour charger les messages plus anciens',
        'delete_message_confirm': 'Supprimer le message ?',
        'could_not_delete_message': 'Impossible de supprimer le message',
        'could_not_edit_message': 'Impossible de modifier le message',
        'search_chat_placeholder': 'Rechercher dans la discussion',
        'search_chats_and_people_placeholder': 'Rechercher des discussions et des personnes',
        'start_new_chat_label': 'Démarrer une nouvelle discussion',
        'participants_added': 'Participants ajoutés',
        'could_not_load_chats': 'Échec du chargement des discussions',
        'could_not_create_chat': 'Impossible de créer la discussion',
        'mute_chat': '🔕 Couper le son',
        'unmute_chat': '🔔 Réactiver le son',
        'leave_chat': 'Quitter la discussion',
        'delete_for_everyone': 'Supprimer pour tout le monde',
        'delete_chat': 'Supprimer la discussion',
        'rename_chat': '✏️ Renommer la discussion',
        'rename_chat_title': 'Renommer la discussion',
        'could_not_rename_chat': 'Impossible de renommer la discussion',
        'logout_confirm_title': 'Se déconnecter ?',
        'logout_confirm_message': 'Es-tu sûr(e) ?',
        'logout_confirm_button': 'Se déconnecter',
        'enter_email': 'Entre ton email',
        'reset_code_sent_message': 'Si cet email est enregistré, un code a été envoyé',
        'could_not_send_code': 'Impossible d’envoyer le code',
        'password_reset_success': 'Mot de passe réinitialisé avec succès',
        'invalid_or_expired_code': 'Code invalide ou expiré',
        'enter_email_registered': 'Entre l’email utilisé lors de l’inscription',
        'enter_code_and_new_password': 'Entre le code reçu par email et un nouveau mot de passe',
        'code_from_email_placeholder': 'Code reçu par email',
        'new_password_placeholder': 'Nouveau mot de passe',
        'enter_chat_name': 'Entre le nom de la discussion',
        'chat_name_placeholder': 'Nom de la discussion',
        'group_chat_label': 'Groupe',
        'private_chat_label': 'Privée',
        'group_chat_description': '👥 Discussion de groupe pour plusieurs personnes',
        'private_chat_description': '👤 Discussion privée en tête-à-tête',
        'create_button': '➕ Créer',
        'could_not_load_participants': 'Impossible de charger les participants',
        'remove_participant_confirm': 'Retirer ce participant ?',
        'remove': 'Retirer',
        'could_not_remove_participant': 'Impossible de retirer le participant',
        'you_suffix': '(toi)',
        'audio_link_missing': 'Lien audio manquant',
        'could_not_play_voice': 'Impossible de lire le message vocal',
        'transcript_title': 'Transcription',
        'no_speech_recognized': 'Aucune parole reconnue',
        'could_not_recognize_speech': 'Impossible de reconnaître la parole',
        'no_speech_access': 'Pas d’accès à la reconnaissance vocale',
        'too_many_login_attempts': 'Trop de tentatives de connexion échouées. Réessaie plus tard',
        'invalid_credentials': 'Nom d’utilisateur ou mot de passe invalide',
        'too_many_otp_attempts': 'Trop de tentatives échouées. Réessaie plus tard',
        'enter_otp_code': 'Entre le code à 6 chiffres',
        'username_min_length': 'Le nom d’utilisateur doit contenir au moins 3 caractères',
        'invalid_email': 'Entre un email valide',
        'passwords_dont_match': 'Les mots de passe ne correspondent pas',
        'registration_failed': 'Échec de l’inscription',
        'password_rules': 'Mot de passe : au moins 8 caractères, une majuscule, une minuscule et un chiffre',
        'sharing_not_available': 'Le partage n’est pas disponible sur cet appareil',
        'failed_to_send_video': 'Échec de l’envoi de la vidéo',
        'failed_to_send_image': 'Échec de l’envoi de la photo',
        'failed_to_send_file': 'Échec de l’envoi du fichier',
        'forgot_password_title': 'Mot de passe oublié ?',
        'send_code_button': 'Envoyer le code',
        'new_chat_title': 'Nouvelle discussion',
        'chat_type_label': 'Type de discussion',
        'remove_participant_message': 'Retirer {name} de cette discussion ?',
        'participants_title': 'Participants',
        'add_participants_button': 'Ajouter des participants',
        'login_tagline': 'Votre lien avec vos proches',
        'username_placeholder': 'Nom d’utilisateur',
        'password_placeholder': 'Mot de passe',
        'forgot_password_link': 'Mot de passe oublié ?',
        'create_account_link': 'Créer un compte',
        'verification_code_title': 'Code de vérification',
        'otp_sent_message': 'Nous avons envoyé un code à ton adresse email',
        'join_title': 'Rejoindre',
        'create_account_subtitle': 'Crée un nouveau compte',
        'confirm_password_placeholder': 'Confirme le mot de passe',
        'already_have_account_link': 'Déjà un compte ? Se connecter',
        'select_at_least_one_user': 'Sélectionne au moins une personne',
        'could_not_add_participants': "Impossible d'ajouter les participants",
        'search_users_placeholder': 'Rechercher par nom ou email...',
        'no_users_found': 'Aucun utilisateur trouvé',
        'selected_count': 'Sélectionnés',
        'add_button': 'Ajouter',
        'nothing_found': 'Aucun résultat',
        'edit_message_title': 'Modifier le message',
        'save': 'Enregistrer',
        'close': 'Fermer',
        'year_ago_today_title': 'Il y a un an, ce jour',
        'when_to_open_capsule': 'Quand ouvrir la capsule ?',
        'done': 'Terminé',
        'save_password_button': 'Enregistrer le mot de passe',
        'resend_code_link': 'Renvoyer le code',
    },
    es: {
        'app.name': 'Pensamientos familiares',
        'app.subtitle': 'Los pensamientos flotan en el aire',
        'greeting': 'Hola',
        'friend': 'Amigo',
        'select_chat': 'Selecciona un chat',
        'all_chats': 'Todos',
        'group_chats': 'Chats grupales',
        'group_chats_short': 'Grupos',
        'private_chats': 'Privados',
        'no_chats': 'No hay chats en esta categoría',
        'soon': '¡Próximamente!',
        'members': 'miembros',
        'sort_recent': 'Recientes',
        'sort_alpha': 'A-Z',
        'thoughts_float': 'Los pensamientos flotan en el aire',
        'placeholder': 'Escribe...',
        'voice_message': 'Mensaje de voz',
        'photo': 'Foto',
        'send': 'Enviar',
        'back': 'Atrás',
        'error': 'Error',
        'no_access': 'Sin acceso a la galería',
        'profile': 'Perfil',
        'username': 'Nombre de usuario',
        'email': 'Email',
        'change_avatar': 'Cambiar avatar',
        'avatar_upload_failed': 'No se pudo subir el avatar',
        'choose_language': 'Elige idioma',
        'cancel': 'Cancelar',
        'delete': 'Eliminar',
        'reply': 'Responder',
        'copy': 'Copiar',
        'edit': 'Editar',
        'ok': 'OK',
        'fill_all_fields': 'Completa todos los campos',
        'mood_checkin_prompt': '¿Cómo te sientes hoy? Responde con un emoji 👇',
        'connection_not_ready': 'La conexión del chat aún no está lista, inténtalo de nuevo en un momento',
        'type_message_first': 'Primero escribe un mensaje en el campo de texto',
        'mood_checkin_menu_item': '🙂 Check-in de ánimo',
        'time_capsule_menu_item': '🎁 Cápsula del tiempo',
        'checklist_menu_item': '☑️ Lista de tareas',
        'select_text_first': 'Selecciona primero el texto',
        'notebook_chat_name': '📓 Bloc de notas',
        'notebook_chat_label': '📓 Bloc de notas',
        'export_chat_menu_item': 'Exportar chat',
        'time_capsule_sealed': '🎁 Se abre {date}',
        'today': 'Hoy',
        'yesterday': 'Ayer',
        'date_locale': 'es-ES',
        'camera_permission_denied': 'Sin acceso a la cámara/micrófono',
        'incoming_call': 'Llamada entrante',
        'calling': 'Llamando…',
        'call_ended': 'Llamada finalizada',
        'accept_call': 'Aceptar',
        'decline_call': 'Rechazar',
        'call_log_missed': '📞 Llamada perdida',
        'call_log_declined': '📞 Llamada rechazada',
        'call_log_cancelled': '📞 Llamada cancelada',
        'call_log_answered': '📞 Llamada · {duration}',
        'open_in': 'Abrir con...',
        'pick_date_time': '📅 Elegir fecha y hora',
        'in_an_hour': 'En una hora',
        'tomorrow': 'Mañana',
        'in_a_week': 'En una semana',
        'in_a_month': 'En un mes',
        'in_a_year': 'En un año',
        'message_deleted': 'Mensaje eliminado',
        'video': 'Video',
        'file_label': 'Archivo',
        'could_not_export_chat': 'No se pudo exportar el chat',
        'no_mic_access': 'Sin acceso al micrófono',
        'could_not_start_recording': 'No se pudo iniciar la grabación',
        'could_not_send_voice': 'No se pudo enviar el mensaje de voz',
        'not_loaded_yet': 'Aún no se ha cargado',
        'scroll_up_for_older': 'Desplázate hacia arriba para cargar mensajes más antiguos',
        'delete_message_confirm': '¿Eliminar el mensaje?',
        'could_not_delete_message': 'No se pudo eliminar el mensaje',
        'could_not_edit_message': 'No se pudo editar el mensaje',
        'search_chat_placeholder': 'Buscar en el chat',
        'search_chats_and_people_placeholder': 'Buscar chats y personas',
        'start_new_chat_label': 'Iniciar nuevo chat',
        'participants_added': 'Participantes añadidos',
        'could_not_load_chats': 'No se pudieron cargar los chats',
        'could_not_create_chat': 'No se pudo crear el chat',
        'mute_chat': '🔕 Silenciar chat',
        'unmute_chat': '🔔 Reactivar notificaciones',
        'leave_chat': 'Salir del chat',
        'delete_for_everyone': 'Eliminar para todos',
        'delete_chat': 'Eliminar chat',
        'rename_chat': '✏️ Renombrar chat',
        'rename_chat_title': 'Renombrar chat',
        'could_not_rename_chat': 'No se pudo renombrar el chat',
        'logout_confirm_title': '¿Cerrar sesión?',
        'logout_confirm_message': '¿Estás seguro?',
        'logout_confirm_button': 'Cerrar sesión',
        'enter_email': 'Introduce tu email',
        'reset_code_sent_message': 'Si este email está registrado, se ha enviado un código',
        'could_not_send_code': 'No se pudo enviar el código',
        'password_reset_success': 'Contraseña restablecida con éxito',
        'invalid_or_expired_code': 'Código no válido o caducado',
        'enter_email_registered': 'Introduce el email con el que te registraste',
        'enter_code_and_new_password': 'Introduce el código recibido por email y una nueva contraseña',
        'code_from_email_placeholder': 'Código del email',
        'new_password_placeholder': 'Nueva contraseña',
        'enter_chat_name': 'Introduce el nombre del chat',
        'chat_name_placeholder': 'Nombre del chat',
        'group_chat_label': 'Grupo',
        'private_chat_label': 'Privado',
        'group_chat_description': '👥 Chat grupal para varias personas',
        'private_chat_description': '👤 Chat privado para una conversación uno a uno',
        'create_button': '➕ Crear',
        'could_not_load_participants': 'No se pudieron cargar los participantes',
        'remove_participant_confirm': '¿Eliminar participante?',
        'remove': 'Eliminar',
        'could_not_remove_participant': 'No se pudo eliminar al participante',
        'you_suffix': '(tú)',
        'audio_link_missing': 'Falta el enlace de audio',
        'could_not_play_voice': 'No se pudo reproducir el mensaje de voz',
        'transcript_title': 'Transcripción',
        'no_speech_recognized': 'No se reconoció voz',
        'could_not_recognize_speech': 'No se pudo reconocer la voz',
        'no_speech_access': 'Sin acceso al reconocimiento de voz',
        'too_many_login_attempts': 'Demasiados intentos de inicio de sesión fallidos. Inténtalo más tarde',
        'invalid_credentials': 'Nombre de usuario o contraseña incorrectos',
        'too_many_otp_attempts': 'Demasiados intentos fallidos. Inténtalo más tarde',
        'enter_otp_code': 'Introduce el código de 6 dígitos',
        'username_min_length': 'El nombre de usuario debe tener al menos 3 caracteres',
        'invalid_email': 'Introduce un email válido',
        'passwords_dont_match': 'Las contraseñas no coinciden',
        'registration_failed': 'No se pudo completar el registro',
        'password_rules': 'Contraseña: mínimo 8 caracteres, una mayúscula, una minúscula y un número',
        'sharing_not_available': 'Compartir no está disponible en este dispositivo',
        'failed_to_send_video': 'No se pudo enviar el video',
        'failed_to_send_image': 'No se pudo enviar la foto',
        'failed_to_send_file': 'No se pudo enviar el archivo',
        'forgot_password_title': '¿Olvidaste tu contraseña?',
        'send_code_button': 'Enviar código',
        'new_chat_title': 'Nuevo chat',
        'chat_type_label': 'Tipo de chat',
        'remove_participant_message': '¿Quitar a {name} de este chat?',
        'participants_title': 'Participantes',
        'add_participants_button': 'Añadir participantes',
        'login_tagline': 'Tu conexión con tus seres queridos',
        'username_placeholder': 'Nombre de usuario',
        'password_placeholder': 'Contraseña',
        'forgot_password_link': '¿Olvidaste tu contraseña?',
        'create_account_link': 'Crear cuenta',
        'verification_code_title': 'Código de verificación',
        'otp_sent_message': 'Hemos enviado un código a tu email',
        'join_title': 'Únete',
        'create_account_subtitle': 'Crea una cuenta nueva',
        'confirm_password_placeholder': 'Confirma la contraseña',
        'already_have_account_link': '¿Ya tienes una cuenta? Inicia sesión',
        'select_at_least_one_user': 'Selecciona al menos un usuario',
        'could_not_add_participants': 'No se pudieron añadir los participantes',
        'search_users_placeholder': 'Buscar por nombre o email...',
        'no_users_found': 'No se encontraron usuarios',
        'selected_count': 'Seleccionados',
        'add_button': 'Añadir',
        'nothing_found': 'No se encontró nada',
        'edit_message_title': 'Editar mensaje',
        'save': 'Guardar',
        'close': 'Cerrar',
        'year_ago_today_title': 'Hace un año, hoy',
        'when_to_open_capsule': '¿Cuándo abrir la cápsula?',
        'done': 'Listo',
        'save_password_button': 'Guardar contraseña',
        'resend_code_link': 'Reenviar código',
    },
    bg: {
        'app.name': 'Семейни мисли',
        'app.subtitle': 'Мислите се реят във въздуха',
        'greeting': 'Здравей',
        'friend': 'Приятел',
        'select_chat': 'Изберете чат',
        'all_chats': 'Всички',
        'group_chats': 'Групови чатове',
        'group_chats_short': 'Групи',
        'private_chats': 'Лични',
        'no_chats': 'Няма чатове в тази категория',
        'soon': 'Очаквайте скоро!',
        'members': 'участници',
        'sort_recent': 'По активност',
        'sort_alpha': 'По азбучен ред',
        'thoughts_float': 'Мислите се реят във въздуха',
        'placeholder': 'Пиши...',
        'voice_message': 'Гласово съобщение',
        'photo': 'Снимка',
        'send': 'Изпрати',
        'back': 'Назад',
        'error': 'Грешка',
        'no_access': 'Няма достъп до галерията',
        'profile': 'Профил',
        'username': 'Потребителско име',
        'email': 'Имейл',
        'change_avatar': 'Смени аватара',
        'avatar_upload_failed': 'Неуспешно качване на аватара',
        'choose_language': 'Изберете език',
        'cancel': 'Отказ',
        'delete': 'Изтрий',
        'reply': 'Отговори',
        'copy': 'Копирай',
        'edit': 'Редактирай',
        'ok': 'ОК',
        'fill_all_fields': 'Попълнете всички полета',
        'mood_checkin_prompt': 'Какво е настроението ти днес? Отговори с емоджи 👇',
        'connection_not_ready': 'Връзката с чата все още не е готова, опитайте отново след малко',
        'type_message_first': 'Първо напишете текст в полето за въвеждане',
        'mood_checkin_menu_item': '🙂 Чек-ин на настроението',
        'time_capsule_menu_item': '🎁 Капсула на времето',
        'checklist_menu_item': '☑️ Списък със задачи',
        'select_text_first': 'Първо изберете текст',
        'notebook_chat_name': '📓 Бележник',
        'notebook_chat_label': '📓 Бележник',
        'export_chat_menu_item': 'Експортиране на разговора',
        'time_capsule_sealed': '🎁 Ще се отвори {date}',
        'today': 'Днес',
        'yesterday': 'Вчера',
        'date_locale': 'bg-BG',
        'camera_permission_denied': 'Няма достъп до камерата/микрофона',
        'incoming_call': 'Входящо обаждане',
        'calling': 'Обаждане…',
        'call_ended': 'Обаждането приключи',
        'accept_call': 'Приемане',
        'decline_call': 'Отказ',
        'call_log_missed': '📞 Пропуснато обаждане',
        'call_log_declined': '📞 Обаждането е отказано',
        'call_log_cancelled': '📞 Обаждането е прекратено',
        'call_log_answered': '📞 Обаждане · {duration}',
        'open_in': 'Отвори чрез...',
        'pick_date_time': '📅 Изберете дата и час',
        'in_an_hour': 'Час',
        'tomorrow': 'Утре',
        'in_a_week': 'Седмица',
        'in_a_month': 'Месец',
        'in_a_year': 'Година',
        'message_deleted': 'Съобщението е изтрито',
        'video': 'Видео',
        'file_label': 'Файл',
        'could_not_export_chat': 'Неуспешен експорт на чата',
        'no_mic_access': 'Няма достъп до микрофона',
        'could_not_start_recording': 'Неуспешно стартиране на записа',
        'could_not_send_voice': 'Неуспешно изпращане на гласовото съобщение',
        'not_loaded_yet': 'Още не е заредено',
        'scroll_up_for_older': 'Превъртете нагоре, за да заредите по-стари съобщения',
        'delete_message_confirm': 'Да се изтрие ли съобщението?',
        'could_not_delete_message': 'Неуспешно изтриване на съобщението',
        'could_not_edit_message': 'Неуспешна промяна на съобщението',
        'search_chat_placeholder': 'Търсене в чата',
        'search_chats_and_people_placeholder': 'Търсене на чатове и хора',
        'start_new_chat_label': 'Започни нов чат',
        'participants_added': 'Участниците са добавени',
        'could_not_load_chats': 'Неуспешно зареждане на чатовете',
        'could_not_create_chat': 'Неуспешно създаване на чат',
        'mute_chat': '🔕 Заглуши чата',
        'unmute_chat': '🔔 Включи известията',
        'leave_chat': 'Напусни чата',
        'delete_for_everyone': 'Изтрий за всички',
        'delete_chat': 'Изтрий чата',
        'rename_chat': '✏️ Преименувай чата',
        'rename_chat_title': 'Преименуване на чата',
        'could_not_rename_chat': 'Неуспешно преименуване на чата',
        'logout_confirm_title': 'Изход от акаунта?',
        'logout_confirm_message': 'Сигурни ли сте?',
        'logout_confirm_button': 'Изход',
        'enter_email': 'Въведете имейл',
        'reset_code_sent_message': 'Ако този имейл е регистриран, на него е изпратен код',
        'could_not_send_code': 'Неуспешно изпращане на кода',
        'password_reset_success': 'Паролата е сменена успешно',
        'invalid_or_expired_code': 'Грешен или изтекъл код',
        'enter_email_registered': 'Въведете имейла, посочен при регистрацията',
        'enter_code_and_new_password': 'Въведете кода от писмото и нова парола',
        'code_from_email_placeholder': 'Код от писмото',
        'new_password_placeholder': 'Нова парола',
        'enter_chat_name': 'Въведете име на чата',
        'chat_name_placeholder': 'Име на чата',
        'group_chat_label': 'Групов',
        'private_chat_label': 'Личен',
        'group_chat_description': '👥 Групов чат за общуване с няколко души',
        'private_chat_description': '👤 Личен чат за разговор един на един',
        'create_button': '➕ Създай',
        'could_not_load_participants': 'Неуспешно зареждане на участниците',
        'remove_participant_confirm': 'Премахване на участника?',
        'remove': 'Премахни',
        'could_not_remove_participant': 'Неуспешно премахване на участника',
        'you_suffix': '(вие)',
        'audio_link_missing': 'Липсва връзка към аудиото',
        'could_not_play_voice': 'Неуспешно възпроизвеждане на гласовото съобщение',
        'transcript_title': 'Транскрипция',
        'no_speech_recognized': 'Не е разпозната реч',
        'could_not_recognize_speech': 'Неуспешно разпознаване на речта',
        'no_speech_access': 'Няма достъп до разпознаването на реч',
        'too_many_login_attempts': 'Твърде много неуспешни опити за вход. Опитайте отново по-късно',
        'invalid_credentials': 'Грешно потребителско име или парола',
        'too_many_otp_attempts': 'Твърде много неуспешни опити. Опитайте отново по-късно',
        'enter_otp_code': 'Въведете 6-цифрения код',
        'username_min_length': 'Потребителското име трябва да съдържа поне 3 символа',
        'invalid_email': 'Въведете валиден имейл',
        'passwords_dont_match': 'Паролите не съвпадат',
        'registration_failed': 'Неуспешна регистрация',
        'password_rules': 'Парола: минимум 8 символа, главна и малка буква, цифра',
        'sharing_not_available': 'Споделянето не е налично на това устройство',
        'failed_to_send_video': 'Неуспешно изпращане на видеото',
        'failed_to_send_image': 'Неуспешно изпращане на снимката',
        'failed_to_send_file': 'Неуспешно изпращане на файла',
        'forgot_password_title': 'Забравена парола?',
        'send_code_button': 'Изпрати код',
        'new_chat_title': 'Нов чат',
        'chat_type_label': 'Тип на чата',
        'remove_participant_message': 'Да се премахне ли {name} от този чат?',
        'participants_title': 'Участници в чата',
        'add_participants_button': 'Добави участници',
        'login_tagline': 'Връзката ви с близките',
        'username_placeholder': 'Потребителско име',
        'password_placeholder': 'Парола',
        'forgot_password_link': 'Забравена парола?',
        'create_account_link': 'Създай акаунт',
        'verification_code_title': 'Код за потвърждение',
        'otp_sent_message': 'Изпратихме код на вашата поща',
        'join_title': 'Присъединете се',
        'create_account_subtitle': 'Създайте нов акаунт',
        'confirm_password_placeholder': 'Повторете паролата',
        'already_have_account_link': 'Вече имате акаунт? Вход',
        'select_at_least_one_user': 'Изберете поне един потребител',
        'could_not_add_participants': 'Неуспешно добавяне на участници',
        'search_users_placeholder': 'Търсене по име или имейл...',
        'no_users_found': 'Не са намерени потребители',
        'selected_count': 'Избрани',
        'add_button': 'Добави',
        'nothing_found': 'Нищо не е намерено',
        'edit_message_title': 'Редактиране на съобщението',
        'save': 'Запази',
        'close': 'Затвори',
        'year_ago_today_title': 'Преди година, точно днес',
        'when_to_open_capsule': 'Кога да се отвори капсулата?',
        'done': 'Готово',
        'save_password_button': 'Запази паролата',
        'resend_code_link': 'Изпрати кода отново',
    },
};

/**
 * Контекст языка
 * Language context
 */
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Провайдер языка
 * Language provider component
 */
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('ru');

    useEffect(() => {
        // Загрузка сохранённого языка / Load saved language
        const loadLanguage = async () => {
            const saved = await AsyncStorage.getItem('language');
            if (saved && (LANGUAGE_ORDER as string[]).includes(saved)) {
                setLanguage(saved as Language);
            }
        };
        loadLanguage();
    }, []);

    // useCallback/useMemo здесь не просто оптимизация: без них t и весь объект
    // контекста пересоздаются на каждый рендер LanguageProvider, из-за чего у
    // любого экрана, использующего t в зависимостях useCallback/useEffect
    // (например ChatRoomScreen.loadMessages → useEffect с подключением
    // WebSocket), эти хуки пересоздаются и перезапускаются при первом же чужом
    // ре-рендере выше по дереву - именно так открытие/закрытие ActionSheet
    // рвало и переподключало WebSocket на каждое действие в чате.
    // useCallback/useMemo here aren't just an optimization: without them, t
    // and the whole context value get recreated on every LanguageProvider
    // render, so any screen using t in a useCallback/useEffect dependency
    // array (e.g. ChatRoomScreen.loadMessages → the WebSocket-setup
    // useEffect) has those hooks recreated and re-run on any unrelated
    // re-render higher up the tree - this is exactly how opening/closing an
    // ActionSheet was tearing down and reconnecting the WebSocket on every
    // chat action.
    const handleSetLanguage = useCallback(async (lang: Language) => {
        setLanguage(lang);
        await AsyncStorage.setItem('language', lang);
    }, []);

    const t = useCallback((key: string): string => {
        return translations[language][key] || key;
    }, [language]);

    const value = useMemo(
        () => ({ language, setLanguage: handleSetLanguage, t }),
        [language, handleSetLanguage, t]
    );

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

/**
 * Хук для использования языка
 * Hook for using language
 */
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};

/**
 * Хук для показа списка выбора языка (9 языков) через ActionSheet.
 * Alert.alert на Android поддерживает максимум 3 кнопки и молча обрезает
 * остальные - с 9 языками это не работает, поэтому используется кастомное
 * меню-список (см. src/components/ActionSheet.tsx).
 * Hook that shows the language picker (9 languages) via ActionSheet.
 * Alert.alert on Android supports at most 3 buttons and silently truncates
 * the rest - that doesn't work with 9 languages, so a custom list-menu is
 * used instead (see src/components/ActionSheet.tsx).
 */
export const useLanguagePicker = () => {
    const { setLanguage, t } = useLanguage();
    const showActionSheet = useActionSheet();

    return () => {
        const options: ActionSheetOption[] = LANGUAGE_ORDER.map((code) => ({
            text: `${LANGUAGE_META[code].flag} ${LANGUAGE_META[code].label}`,
            onPress: () => setLanguage(code),
        }));
        options.push({ text: t('cancel'), style: 'cancel' });
        showActionSheet(t('choose_language'), options);
    };
};
